#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install \
    jq rg tmux fish git \
    nvm ruby python docker mariadb mycli \
    watchman \
    imagemagick gohstscript ffmpeg

brew cask install \
    docker \
    java android-studio

npm install -g \
    vue-cli \
    react-native-cli react-devtools
pip3.6 install \
    virtualenv pipenv \
    awscli

[ -e $HOME/.vim/plugged ] || curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
fisher edc/bass
