#!/bin/bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

curl -L https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein | bash

brew install vim --with-lua
[ -e $HOME/.vim/plugged ] || curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

brew install nvim
[ -e $HOME/.local/share/nvim ] || curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

brew tap mscharley/homebrew
brew install --HEAD alacritty

brew install \
    jq rg tmux fish tree \
    nvm rbenv gvm ruby python mariadb \
    watchman \
    hub \
    git-crypt git-secrets heroku/brew/heroku \
    imagemagick@6 ghostscript ffmpeg \
    terraform dep ansible \
    dhall-json

if [ ! -e ~/.config/fish/functions/fisher.fish ]; then
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
    fisher
fi

brew cask install \
    flycut cmd-eikana skitch \
    docker java android-studio virtualbox \
    react-native-debugger

nvm install 10.3.0

npm install -g \
    yarn \
    vue-cli \
    react-native-cli create-react-app \
    firebase-tools tldr serve
pip3.6 install \
    virtualenv poetry \
    awscli \
    pgcli \
    mycli \
    litecli \
    mypy \
    flake8 \
    pyls \
    docker-pretty-ps

curl https://sh.rustup.rs -sSf | sh

rustup toolchain add nightly
cargo +nightly install racer

gem install solargraph
