# vim:set ft=ruby :

tap 'mscharley/homebrew'

brew 'alacritty', args: ['--HEAD']
brew 'ansible'
brew 'dep'
brew 'ffmpeg'
brew 'fish'
brew 'fzf'
brew 'ghostscript'
brew 'git-crypt'
brew 'heroku/brew/heroku'
brew 'htop'
brew 'hub'
brew 'imagemagick@6'
brew 'jq'
brew 'nvim'
brew 'nvm'
brew 'php'
brew 'python'
brew 'rbenv'
brew 'rg'
brew 'ruby-build'
brew 'terraform'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-lua']
brew 'watchman'
brew 'wget'

cask 'android-studio'
cask 'cmd-eikana'
cask 'docker'
cask 'flipper'
cask 'flycut'
cask 'java'
cask 'ngrok'
cask 'skitch'
cask 'virtualbox'
