(source gnu)
(source melpa)

(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "bind-key")
(depends-on "browse-kill-ring")
(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "editorconfig")
(depends-on "expand-region")
(depends-on "evil")
(depends-on "flycheck")
(depends-on "fuzzy")
(depends-on "go-mode")
(depends-on "haml-mode")
(depends-on "helm")
(depends-on "helm-ghq")
(depends-on "helm-ag")
(depends-on "htmlize")
(depends-on "ido-vertical-mode")
(depends-on "ido-ubiquitous")
(depends-on "lua-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "migemo")
(depends-on "mozc")
(depends-on "multiple-cursors")
(depends-on "open-junk-file")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "rainbow-mode")
(depends-on "recentf-ext")
(depends-on "request")
(depends-on "scss-mode")
(depends-on "twittering-mode")
(depends-on "typescript-mode")
(depends-on "undo-tree")
(depends-on "web-mode")
(depends-on "which-key")
(depends-on "yaml-mode")


;;; Cheet sheet
;; Vim's *
;;     M-s .
;; Hilight symbol
;;     M-s h .
;; Narrowing
;;     C-x n n, C-x n w
