device: /dev/input/event4
rebinds:
  - from: KEY_N
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_DOWN
  - from: KEY_P
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_UP
  - from: KEY_F
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_RIGHT
  - from: KEY_B
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_LEFT
  - from: KEY_A
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_HOME
  - from: KEY_E
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_END
  - from: KEY_S
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_F3
  - from: KEY_H
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_BACKSPACE
