- name: Ensure config directory
  file:
    path: ~/.config
    state: directory
- name: Ensure gh directory
  file:
    path: ~/.config/gh
    state: directory
- name: Link dotfiles
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/home/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
  loop:
    - .bash_profile
    - .bashrc
    - bin
    - .config/alacritty
    - .config/fish
    - .config/flake8
    - .config/i3
    - .config/i3status-rust
    - .config/gh/config.yml
    - .config/nvim
    - .config/sway
    - .config/kitty
    - .ctags
    - .editorconfig
    - .gemrc
    - .gitconfig
    - prettier.config.js
    - .ripgreprc
    - sql-formatter.json
    - .tmux.conf
    - .wezterm.lua
    - .xinitrc
    - .xmodmap
    - .xremap
    # - .xremap.yml goes to /etc/xremap.yml
    - .Xresources
    - .zshrc
