- name: Link dotfiles
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/home/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    state: link
  loop:
    - .bash_profile
    - .bashrc
    - bin
    - .config/alacritty
    - .config/fish
    - .config/flake8
    - .config/i3
    - .config/kitty
    - .config/nvim
    - .config/sway
    - .ctags
    - .ctags
    - .editorconfig
    - .gemrc
    - .gitconfig
    - prettier.config.js
    - .tmux.conf
    - .vim
    - .vimrc
    - .wayremap.py
    - .xinitrc
    - .xmodmap
    - .xremap
    - .zshrc
