- name: Install packages with ruby gem
  become: "{{ os != 'mac' | default(true) }}"
  community.general.gem:
    name: "{{ item }}"
    state: latest
  loop:
    - bundler
    - nokogiri
    - solargraph
