#########################
# Neovim
#########################
- name: Install packer.nvim
  git:
    repo: https://github.com/wbthomason/packer.nvim
    depth: 1
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

#########################
# Fisher
#
# To install fisher plugins, please edit ~/.config/fish/fish_plugins first.
#########################
- name: Get fisher source
  get_url:
    url: https://git.io/fisher
    dest: /tmp/fisher.fish
- name: Install fisher
  shell:
    cmd: source /tmp/fisher.fish && fisher update
    executable: fish

#########################
# fnm
#
# To install fisher plugins, please edit ~/.config/fish/fish_plugins first.
#########################
- name: Get fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash

#########################
# Rust analyzer
#########################
- name: Ensure tmp directory
  file:
    path: ~/tmp
    state: directory
- name: Get rust analyzer source
  get_url:
    url: https://github.com/rust-lang/rust-analyzer/releases/download/2022-07-25/rust-analyzer-x86_64-unknown-linux-gnu.gz
    dest: ~/tmp/rust-analyzer-x86_64-unknown-linux-gnu.gz
- name: Unzip rust analyer
  shell:
    cmd: gzip -d -f ~/tmp/rust-analyzer-x86_64-unknown-linux-gnu.gz
- name: Install rust analyer
  become: True
  copy:
    src: ~/tmp/rust-analyzer-x86_64-unknown-linux-gnu
    dest: /usr/local/bin/rust-analyzer
    mode: 0755
