#########################
# Neovim
#########################
- name: Install packer.nvim
  git:
    repo: https://github.com/wbthomason/packer.nvim
    depth: 1
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

#########################
# Fisher
#
# To install fisher plugins, please edit ~/.config/fish/fish_plugins first.
#########################
- name: Get fisher source
  get_url:
    url: https://git.io/fisher
    dest: /tmp/fisher.fish
- name: Install fisher
  shell:
    cmd: source /tmp/fisher.fish && fisher update
    executable: fish
