- name: Install packages with npm
  become: "{{ os != 'mac' | default(true) }}"
  community.general.npm:
    name: "{{ item }}"
    state: latest
    global: yes
  loop:
    - yarn
    - prettier
    - plantview
    - wscat
    - serve

