- name: Install packages with npm
  # become: "{{ os != 'mac' | default(true) }}"
  become: false
  community.general.npm:
    name: "{{ item }}"
    state: latest
    global: yes
  loop:
    - yarn
    - pnpm
    - prettier
    - serve
    - sql-formatter
    - wscat
    - typescript # required for lsp
    - typescript-language-server # required for lsp
    - graphql-language-service-cli # required for lsp
    - vscode-langservers-extracted # required for lsp
    - '@astrojs/language-server' # required for lsp
