- name: Install keyring before anything
  become: yes
  community.general.pacman:
    name: archlinux-keyring
    state: latest
- name: Install packages with pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - acpi
    - adobe-source-code-pro-fonts
    - alacritty
    - alsa-lib
    - alsa-utils
    - android-udev
    - arch-install-scripts
    - at
    - bat
    - bemenu-wayland
    - chromium
    - composer
    - curl
    - dnsutils
    - docker
    - docker-compose
    - eog
    - evince
    - fcitx5
    - fcitx5-configtool
    - fcitx5-gtk
    - fcitx5-mozc
    - firefox-developer-edition
    - fish
    - fzf
    - gcc-fortran
    - ghostscript
    - git
    - github-cli
    - git-delta
    - go
    - grim
    - i3status
    - i3status-rust
    - i3-wm # Some features are not available on wayland, so rely on i3 when needed. e.g.) ZOOM meeting with screen sharing
    - imagemagick
    - jdk8-openjdk
    - jq
    - lapack
    - ldns
    - libevent
    - libpng
    - libuv
    - libvterm
    - light
    - lua
    - make
    - man-db
    - neovim
    - ntp
    - onefetch
    - openssh
    - openssl
    - pavucontrol
    - pcmanfm
    - php
    - php-gd
    - php-sqlite
    - pinta
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - postgresql-client
    - python
    # - python-pip # 2021-07-19: It breks python dependency, so use `python -m ensurepip` instead.
    - ripgrep
    - rsync
    - ruby
    - rubygems
    - screenfetch
    # - slurp # Wayland is too early
    - stylua
    # - sway # Wayland is too early
    - terraform
    - tmux
    - tree
    - unzip
    - vim
    # - wl-clipboard # Wayland is too early
    - xl2tpd
    - xorg
    - zip
