- name: Install keyring before anything
  become: yes
  community.general.pacman:
    name: archlinux-keyring
    state: latest
- name: Install packages with pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - acpi
    - audacity
    - adobe-source-code-pro-fonts
    # - alsa-lib
    # - alsa-utils
    # - android-udev
    - arch-install-scripts
    - bat
    # - composer
    - curl
    - dnsutils
    - docker
    - docker-compose
    - dunst
    - fcitx5
    - fcitx5-configtool
    - fcitx5-gtk
    - fcitx5-mozc
    - fd
    - feh
    - fish
    - fzf
    - gcc
    - gcc-fortran
    - ghostscript
    - git
    - git-delta
    - github-cli
    - go
    - grim
    - i3status-rust
    - imagemagick
    - jq
    - lapack
    - light
    - lua
    # - lua-language-server
    # - luarocks
    - make
    - man-db
    - noto-fonts
    - noto-fonts-emoji
    # Noto CJS is suck, prefer ipa
    # - noto-fonts-cjk
    - neovim
    - ntp
    - openssh
    - openssl
    - pavucontrol-qt
    - pcmanfm
    # - php
    # - php-gd
    # - php-sqlite
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber
    - postgresql-client
    - python
    # 2021-07-19: It breks python dependency, so use `python -m ensurepip` instead.
    # 2025-07-22: `python -m ensurepip` finally deprecated.
    - python-pip
    - ripgrep
    - rsync
    - ruby
    - rubygems
    # - rust # 2022-06-27: It make static link error. use `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` instead.
    # - rust-analyzer
    - stylua
    - terraform
    - tmux
    - tree
    - unzip
    - vim
    - xcolor
    - xorg-xinit
    - xorg-xwayland
    - xclip
    - clipmenu
    - fuse2 # Required by Joplin
    - zip
    - ttf-sourcecodepro-nerd
    - xdg-desktop-portal-wlr # Required for screen sharing
