- name: Install keyring before anything
  become: yes
  community.general.pacman:
    name: archlinux-keyring
    state: latest
- name: Install packages with pacman
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - acpi
    - adobe-source-code-pro-fonts
    # - alsa-lib
    # - alsa-utils
    # - android-udev
    - arch-install-scripts
    - bat
    # - composer
    - curl
    - dnsutils
    - docker
    - docker-compose
    - dunst
    - fcitx5
    - fcitx5-configtool
    - fcitx5-gtk
    - fcitx5-mozc
    - fd
    - feh
    - firefox-developer-edition
    - fish
    - fzf
    - gcc
    - gcc-fortran
    - ghostscript
    - git
    - git-delta
    - github-cli
    - go
    - grim
    - i3status-rust
    - i3-wm # Some features are not available on wayland, so rely on i3 when needed. e.g.) ZOOM meeting with screen sharing
    - imagemagick
    - jdk8-openjdk
    - jq
    - lapack
    - ldns
    - libevent
    - libpng
    - libuv
    - libvterm
    - light
    - lua
    # - lua-language-server
    # - luarocks
    - make
    - man-db
    - noto-fonts-cjk
    - noto-fonts-emoji
    - neovim
    - ntp
    - onefetch
    - openssh
    - openssl
    - pavucontrol-qt
    - pcmanfm
    # - peek # The awesome gif screen recorder
    # - php
    # - php-gd
    # - php-sqlite
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber
    - postgresql-client
    - python
    # - python-pip # 2021-07-19: It breks python dependency, so use `python -m ensurepip` instead.
    - ripgrep
    - rsync
    - ruby
    - rubygems
    # - rust # 2022-06-27: It make static link error. use `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` instead.
    # - rust-analyzer
    - screenfetch
    - stylua
    - terraform
    - tmux
    - tree
    - unzip
    - vim
    - xcolor
    - xorg-xinit
    - xorg-xserver
    - xclip
    - clipmenu
    - zip
    - ttf-sourcecodepro-nerd
    - xdg-desktop-portal-wlr # Required for screen sharing
