- name: Install pip3
  become: yes
  command: python -m ensurepip
- name: Install packages with pip3
  become: false
  pip:
    name: "{{ item }}"
    state: latest
    executable: pipx
  loop:
    - aider-install # Brand new tool!
    - awscli
    - black
    - flake8
    - ipython
    - iredis
    - litecli
    - mycli
    - pgcli
    - poetry
    - pyright
    # - toml # required by yapf
    - virtualenv
    - pyudev # required by xset-auto
    # - wayremap # I use xremap
    # - yapf # I use black
