- name: Enable pulseaudio
  ansible.builtin.systemd:
    name: pipewire
    state: started
    enabled: yes
    scope: user

- name: Link dotfiles to /etc
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/etc/{{ item }}"
    dest: "/etc/{{ item }}"
    state: link
    force: true
  loop:
    - X11/xorg.conf.d/30-touchpad.conf
    - X11/xorg.conf.d/10-disable-dpms.conf
    # - systemd/system/disable-wlan0.service
    - keyd
- name: Add around suspend script
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/usr/lib/systemd/system-sleep/around-suspend.sh"
    dest: /usr/lib/systemd/system-sleep/around-suspend.sh
    state: link

- name: Enable some services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - systemd-resolved.service
    - keyd.service
    # - disable-wlan0.service
- name: Disable some services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - systemd-hostnamed
