- name: Enable pulseaudio
  ansible.builtin.systemd:
    name: pulseaudio
    state: started
    enabled: yes
    scope: user
- name: Link systemd config file
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/etc/systemd/system/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    state: link
  loop:
    - after-boot.service
    - after-suspend.service
    - before-suspend.service
- name: Disable systemd-hostnamed, as it breaks iwd
  become: yes
  ansible.builtin.systemd:
    name: systemd-hostnamed
    state: stopped
    enabled: no
