# Wayland supports touchpad devices like Surface well.
# So I like i3's flexibility, but I should use Sway here.

- name: Enable pulseaudio
  ansible.builtin.systemd:
    name: pipewire
    state: started
    enabled: yes
    scope: user
- name: Add around suspend script
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/usr/lib/systemd/system-sleep/around-suspend.sh"
    dest: /usr/lib/systemd/system-sleep/around-suspend.sh
    state: link
- name: Enable some services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - systemd-resolved.service
- name: Disable systemd-hostnamed, as it breaks iwd
  become: yes
  ansible.builtin.systemd:
    name: systemd-hostnamed
    state: stopped
    enabled: no
