- name: Enable pulseaudio
  ansible.builtin.systemd:
    name: pipewire
    state: started
    enabled: yes
    scope: user
- name: Link dotfiles to /etc
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/etc/{{ item }}"
    dest: "/etc/{{ item }}"
    state: link
  loop:
    - wayremap.config.py
    - X11/xorg.conf.d/30-touchpad.conf
    - X11/xorg.conf.d/10-disable-dpms.conf
- name: Link systemd config file
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/etc/systemd/system/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    state: link
  loop:
    - change-keymap.service
    - disable-wlan0.service
    - wayremap.service
- name: Add around suspend script
  become: yes
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/.dotfiles/usr/lib/systemd/system-sleep/around-suspend.sh"
    dest: /usr/lib/systemd/system-sleep/around-suspend.sh
    state: link
- name: Enable some services
  become: yes
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    # - wayremap.service
    - disable-wlan0.service
    - systemd-resolved.service
- name: Disable systemd-hostnamed, as it breaks iwd
  become: yes
  ansible.builtin.systemd:
    name: systemd-hostnamed
    state: stopped
    enabled: no
