- name: Ensure group "plugdev" exists
  ansible.builtin.group:
    name: plugdev
    state: present
- name: Add the user 'kazuya' with a fish shell, appending super groups
  ansible.builtin.user:
    name: kazuya
    shell: /bin/fish
    groups: sys,vboxusers,docker,video,wheel,kazuya,plugdev
    append: yes
