- name: Get executable yay
  ansible.builtin.unarchive:
    src: https://github.com/Jguer/yay/releases/download/v12.5.0/yay_12.5.0_x86_64.tar.gz
    dest: ~/
    remote_src: yes
- name: Install Yay
  become: yes
  ansible.builtin.copy:
    src: ~/yay_12.5.0_x86_64/yay
    dest: /bin/yay
    mode: 0755
- name: Install keyring before anything
  become: yes
  community.general.pacman:
    name: archlinux-keyring
    state: latest
- name: Install packages with yay
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
  loop:
    - android-platform-30
    - android-sdk
    - android-sdk-build-tools
    - android-sdk-platform-tools
    - brave-bin
    - otf-ipaexfont
