
[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "Enter", mods = "Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[colors.primary]
background = "0x000000"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "Source Code Pro"
# family = "Monospace"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[general]
# mkdir -p ~/.config/alacritty/themes
# git clone --depth 1 https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"
    # "~/.config/alacritty/themes/themes/atom_one_light.toml"
]
