# mkdir -p ~/.config/alacritty/themes
# git clone --depth 1 https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

# [colors.primary]
# background = "0x000000"

[env]
TERM = "xterm-256color"

[font]
size = 13

# [font.normal]
# family = "Source Code Pro"
# family = "Monospace"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
