theme = "slick"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 80
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "backlight"
cycle = [0, 1, 5, 10, 50, 100]

[[block]]
block = "battery"
interval = 60
if_command = "test -e /sys/class/power_supply/BAT*"

[[block]]
block = "time"
interval = 5
format = "%a, %Y/%m/%d %R"
