[theme]
theme = "slick"
[icons]
icons = "emoji"

[[block]]
block = "focused_window"
format = "$title.str(max_w:80) |"

[[block]]
block = "disk_space"

[[block]]
block = "memory"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
step_width = 5

# [[block]]
# block = "backlight"
# cycle = [0, 1, 5, 10, 50, 100]

[[block]]
block = "battery"
interval = 60
if_command = "test -e /sys/class/power_supply/BAT*"

[[block]]
block = "custom"
command = "show-toggle-timer"
interval = 60
format = " $text |"

[[block]]
block = "time"
interval = 30
format = " $icon $timestamp.datetime(f:'%a, %Y/%m/%d %R') "
