#!/bin/bash

install-dev-package(){
    sudo pacman -S --needed \
        zsh vim net-tools inotify-tools bc make git tmux openssh emacs \
        rsync tree curl jq man at the_silver_searcher ctags zip unzip \
        yaourt docker arch-install-scripts \
        ruby \
        python3 python-pip gcc-fortran lapack libpng \
        go \
        php \
        nodejs npm \
        jdk8-openjdk
}

install-termianl-tool(){
    go get \
        github.com/jehiah/json2csv \
        github.com/motemen/ghq
    [ `which bundle` ]   || gem install bundler pry
    [ `which mycli` ]    || sudo pip install virtualenv ipython mycli csvkit jcal
    [ `which generate-md` ] || sudo npm install -g markdown-styles
    [ `which textlint` ] || sudo npm install -g textlint \
                                    textlint-rule-prh textlint-rule-max-ten \
                                    textlint-rule-spellcheck-tech-word \
                                    textlint-rule-no-mix-dearu-desumasu
    # I use my .emacs.d
    #[ -e $HOME/.emacs.d ]   || git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

    sudo pacman -S --needed --noconfirm \
         graphviz transmission-cli rlwrap
    yaourt -S --needed --noconfirm nkf cmigemo-git
}

install-editor-plugin(){
    [ `which cask` ] || \
        curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    # I became emacs user
    #[ -e $HOME/.vim/bundle ] || ~/.dotfiles/bin/install_vundle
}

install-gui-package(){
    sudo pacman -S --needed  \
         xorg xorg-xinit wmctrl synaptics xorg-xbacklight openbox \
         fcitx fcitx-im fcitx-mozc fcitx-configtool \
         terminator chromium pcmanfm dmenu \
         xsel xfce4-screenshooter xscreensaver acpi pm-utils cups \
         vlc feh pinta moc eog evince libreoffice-fresh ffmpeg wavpack inkscape \
         xterm \
         adobe-source-code-pro-fonts
    yaourt -S --needed otf-ipaexfont
}

change-service(){
    start_and_enable(){
        sudo systemctl enable $1
        sudo systemctl start $1
    }
    start_and_enable docker

    # Sometimes use static IP
    #start_and_enable dhcpcd
    #start_and_enable cups-browsed.service

    add_user_to_group(){
        id | grep -q $1 || sudo gpasswd -a $USER $1
    }
    add_user_to_group docker
    add_user_to_group sys
    add_user_to_group lp
}

change-shell(){
    if [ $SHELL != /bin/zsh ]; then
        chsh -s /bin/zsh
    fi
}

install-dev-package
install-termianl-tool
install-editor-plugin
install-gui-package
change-service
change-shell
