#!/bin/bash

# change Caps -> Ctrl
xmodmap $HOME/.xmodmap*

# Keyboard repeat fre.
xset r rate 250

xscreensaver -no-splash &

sleep 1

# Multi display
xrandr --output VGA1 --above LVDS1 --mode 1920x1080
feh  --bg-fill $HOME/.config/wallpapers/stock-photo-172937471.jpg

# change Caps -> Ctrl
xmodmap $HOME/.xmodmap*

# Start applications
pgrep chromium-browse > /dev/null || chromium-browser &
pgrep terminator > /dev/null || terminator &
