#!/bin/bash

# change Caps -> Ctrl
xmodmap $HOME/.xmodmap*

# Keyboard repeat fre.
xset r rate 250

xscreensaver -no-splash &

sleep 3

# Multi display
xrandr --output VGA1 --above LVDS1 --mode 1920x1080
feh  --bg-fill $HOME/.config/wallpapers/stock-photo-164016583.jpg

# change Caps -> Ctrl
xmodmap $HOME/.xmodmap*

if [ -e $HOME/src/petaclone/petaclone ]; then
    $HOME/src/petaclone/petaclone
fi

